# The release drafter configuration file
name-template: 'Release ${version}'
tag-template: 'v${version}'
change-template: '- ${title} (#${number}) by @${author}'
version-template: '$MAJOR.$MINOR.$PATCH$PRERELEASE'

# Categories define how issues and PRs are grouped in the changelog
categories:
  - title: '🚀 Features'
    labels: ['feature', 'feat']
  - title: '🐛 Fixes'
    labels: ['bug', 'fix', 'bugfix']
  - title: '📚 Documentation'
    labels: ['docs', 'documentation']
  - title: '🛠 Maintenance'
    labels: ['chore', 'refactor', 'maintain']
  - title: '🎨 Styling'
    labels: ['style', 'css', 'ui', 'ux']
  - title: '🔧 Configuration'
    labels: ['config', 'configuration', 'setup']
  - title: '⚡ Performance'
    labels: ['perf', 'optimization', 'performance']
  - title: '✅ Tests'
    labels: ['test', 'testing', 'ci', 'unit-test']
  - title: '🔒 Security'
    labels: ['security', 'vuln']
  - title: '⚙️ Build'
    labels: ['build', 'ci/cd', 'pipeline']

# Additional configuration options
exclude-labels: [] # Labels to exclude from being included in the changelog
include-labels: [] # Labels that should always be included
include-paths: [] # Paths that should always be included in the changelog
exclude-contributors: [] # Contributors to exclude

# The template for the header of the release notes
header: |
  ## Changelog for ${version} - ${date}

# The footer of the release notes
footer: |
  _This changelog was automatically generated by Release Drafter_

# Sorting configuration
sort-by: 'merged_at'
sort-direction: 'descending'

# Versioning configuration
prerelease: false
prerelease-identifier: '' # Identifier for pre-releases, if any
include-pre-releases: false # Whether to include pre-releases in the changelog

# Filters (optional)
latest: true # Include the latest release
filter-by-commitish: false # Filter changes by commitish, if needed
commitish: '' # The commit hash to filter by

# Template for categories in the changelog
category-template: '## $TITLE'

# If no changes exist, display this message
no-changes-template: '- No significant changes in this release.'

# Optional replacers for change titles or messages
replacers: []

# Auto-labeler configuration (optional)
autolabeler: []

# Change title escape mechanism (optional)
change-title-escapes: ''
