name: 'JavaScript and TypeScript Linting'

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Run ESLint
        run: |
          npm run lint
