name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Release Draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Changelog
        run: |-
          git config --global user.name "ReleaseBot"
          git config --global user.email "releasebot@example.com"
          git add ./changelog/CHANGELOG.md
          git commit -m "📝 docs(bot): Auto update changelog for release v${{ github.run_number }}"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}