name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: release-drafter/release-drafter@v6
        with:
          config-name: .github/release-drafter.yml
          output-name: changelog.md
          output-path: ./changelog/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changelog to changelog folder
        run: |
          git config --global user.email "themesyed@gmail.com"
          git config --global user.name "Your Name"
          git add changelog/changelog.md
          git commit -m "Update changelog"
          git push
