name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ secrets.BUN_VERSION }}

      - name: Workflow
        run: bun run workflow:readme

      - name: Commit and push changelog to changelog folder
        run: |
          git config --global user.email "themesyed@gmail.com"
          git config --global user.name "tasker"
          git add .
          git commit -m "📝 docs(bot): Auto sync agents & plugin to readme" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
