name: Release Drafter Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    types: [opened, reopened, synchronize]  # Trigger on pull request events

permissions:
  contents: read  # Read access to repository content for generating changelog

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest  # Runs the workflow on the latest Ubuntu runner

    permissions:
      contents: write  # Write access to repository content to create a draft
      pull-requests: write  # Write access to pull requests to update drafts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out the repository code

      - name: Set up Release Drafter
        uses: release-drafter/release-drafter@v6  # Use Release Drafter to generate changelog

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

      - name: Commit and push changes
        run: |
          git config --global user.name "Release Drafter Bot"
          git config --global user.email "release-drafter@github.com"
          git add .  # Add any changes made by Release Drafter
          git commit -m "docs🗒️: update release drafter changelog" || exit 0  # Commit changes if any
          git push  # Push changes to the repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

