name: Run tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies with npm
        run: npm install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '6.0'

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..30}; do
            if nc -z localhost 27017; then
              echo "MongoDB is ready"
              break
            fi
            echo "Waiting for MongoDB..."
            sleep 2
          done

      - name: Set up Google Cloud credentials
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > $HOME/google-service.json
          gcloud auth activate-service-account --key-file=$HOME/google-service.json

      - name: Run tests with npm
        run: npm test
        env:
          CI: true
          MONGO_URI: mongodb://localhost:27017
          MONGO_DB_NAME: test
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/google-service.json
