name: Test CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval \"db.runCommand({ ping: 1 })\""
          --health-interval=15s
          --health-timeout=15s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start services using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..30}; do
            if nc -z mongodb 27017; then
              echo "MongoDB is ready"
              break
            fi
            echo "Waiting for MongoDB..."
            sleep 2
          done

      - name: Check MongoDB logs
        run: docker logs mongodb

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        env:
          JWT_SECRET: '123123'
          MONGO_URI: mongodb://mongodb:27017 # Using service name
          MONGO_DB_NAME: test
        run: pnpm run test

      - name: Clean up
        run: docker-compose down -v
