name: Test CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        volumes:
          - mongo-data:/data/db
        networks:
          - mynetwork

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Set up Docker Compose
        run: |
          sudo apt-get install docker-compose

      - name: Build and start services using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..30}; do
            if nc -z localhost 27017; then
              echo "MongoDB is ready"
              break
            fi
            echo "Waiting for MongoDB..."
            sleep 2
          done

      - name: Run tests
        env:
          JWT_SECRET: '123123'
          MONGO_URI: mongodb://mongodb:27017
          MONGO_DB_NAME: test
        run: pnpm run test

      - name: Clean up
        run: docker-compose down
